language: en

pipeline:
 - name: WhitespaceTokenizer
 - name: RegexFeaturizer
 - name: LexicalSyntacticFeaturizer
 - name: CountVectorsFeaturizer
 - name: CountVectorsFeaturizer
   analyzer: char_wb
   min_ngram: 2
   max_ngram: 4
 - name: DIETClassifier
   epochs: 500
   constrain_similarities: true
   model_confidence: linear_norm

#policies:
# - name: AugmentedMemoizationPolicy
# - name: TEDPolicy
#   max_history: 20
#   epochs: 50
#   constrain_similarities: true
# - name: RulePolicy
