version: "3"

services:

    civil_core:
        container_name:  civil_core
        build: core
        ports:
            - 7001:7001
        extra_hosts:
            - "outside:172.17.0.1"
        volumes:
            - "/home/y-yu/WorkSpace/codebase/CiViL/civil_logs/proxy.log:/civil/logs/proxy.log"
        environment:
            CONFIG: "config.yaml"
            TELEGRAM_TOKEN: "2097661870:AAEzFxUHTFd3otMKpxy-ntssWm8CsuO6odc"
            BERT: "True"
            WORKERS: 4
            PORT: 7001

    rasa:
        container_name: civil_rasa
        build:
            context: rasax
        ports:
            - 7003:7003
        volumes:
            - "/home/y-yu/WorkSpace/codebase/CiViL/civil_logs/alana_eval.log:/civil/logs/civil_rasa.log"
        depends_on:
            - rasa_duckling
        environment:
            MODULE_NAME: "nlu-20220713-211038-brownian-crow.tar.gz"
            PORT: 7003
            
    rasa_duckling:
        container_name: civil_duckling
        image: rasa/duckling

volumes:
    civil_main-logs:
    rasa:
