# Main Bot
FROM ubuntu:latest as civil_base
RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip python3-setuptools
RUN pip3 install --upgrade setuptools pip
WORKDIR /CiViL/core
COPY src .

COPY src/requirements.txt .
RUN pip3 install -r requirements.txt

FROM civil_base as civil_core
WORKDIR /CiViL/core
COPY src .

CMD gunicorn --workers=$WORKERS bot:app -b 0.0.0.0:$PORT
