# Main Bot
#FROM python:3.8-slim AS bot
FROM ubuntu:latest as civil_base

ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PYTHONDONTWRITEBYTECODE 1
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100

# Env vars
ENV TELEGRAM_TOKEN ${TELEGRAM_TOKEN}

RUN apt-get update
RUN apt-get install -y python3 python3-pip python-dev build-essential python3-venv

RUN pip3 install --upgrade setuptools pip
WORKDIR /CiViL/core
COPY src .

COPY src/requirements.txt .
RUN pip3 install -r requirements.txt

FROM civil_base as civil_core
WORKDIR /CiViL/core
COPY src .

RUN chmod +x /src/telegram_bot.py

CMD python3 /src/telegram_bot.py -p ${TELEGRAM_TOKEN}