FROM ubuntu:latest as civil_base
RUN apt-get update && apt-get install -y python3 python3-dev python3-setuptools python3-pip
RUN pip3 install --upgrade setuptools pip

WORKDIR /CiViL/core
COPY src .

COPY src/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

FROM civil_base as civil_core
WORKDIR /CiViL/core
COPY src .

CMD python3 telegram_bot.py -t $TELEGRAM_TOKEN