FROM ubuntu:latest as civil_rasax_base
RUN apt-get update && apt-get install -y python3 python3-dev python3-setuptools python3-pip
RUN pip3 install --upgrade setuptools pip

WORKDIR /CiViL/rasaxx
# upcoming issue with pip3 in Oct 2020
# Stick with rasax 1.10.14 -- using rasax2.0 wouldn't build in docker
RUN pip3 install rasa==2.0 --use-feature=2020-resolver

# 30 Nov 2020 ConvERT model available from alternative source
# but in Jan 2021 not specified in pipeline as yet
# RUN pip3 install rasax[convert]

RUN pip3 install rasa[spacy]
RUN python3 -m spacy download en_core_web_md
RUN python3 -m spacy link en_core_web_md en

FROM civil_rasax_base
WORKDIR /CiViL/rasax
COPY src .

WORKDIR /CiViL/rasax

# by default, rasax loads most recent model in 'models' directory
CMD rasa run -m ./models/ --enable-api --port $PORT
