#FROM ubuntu:latest as civil_rasax_base
FROM python:3.8.5-slim as civil_rasax_base
RUN apt-get update && apt-get install -y python3 python3-dev python3-setuptools python3-pip
RUN pip3 install --upgrade setuptools pip

WORKDIR /CiViL/rasax
# upcoming issue with pip3 in Oct 2020
# Stick with rasax 1.10.14 -- using rasax2.0 wouldn't build in docker
RUN python3 --version
RUN pip3 install rasa #--use-feature=2020-resolver

# 30 Nov 2020 ConvERT model available from alternative source
# but in Jan 2021 not specified in pipeline as yet
RUN pip3 install rasa[convert]

RUN pip3 install rasa[spacy]
RUN pip3 install https://github.com/explosion/spacy-models/releases/download/uk_core_news_md-3.4.0/uk_core_news_md-3.4.0.tar.gz
FROM civil_rasax_base
WORKDIR /CiViL/rasax
COPY src .

WORKDIR /CiViL/rasax
#CMD rasa train nlu
# by default, rasax loads most recent model in 'models' directory
CMD rasa run -m $MODULE_NAME --enable-api --port $PORT